# Generated by Django 5.2.4 on 2025-07-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbCidade',
            fields=[
                ('co_seq_cidade', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=44)),
            ],
            options={
                'db_table': 'tb_cidade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbConfigEtl',
            fields=[
                ('co_config_etl', models.IntegerField(primary_key=True, serialize=False)),
                ('st_ativo', models.IntegerField(db_comment='Indica se o ETL est� ativo. 1 - Ativo. 2 - Inativo')),
                ('data_atualizacao_inicial', models.DateField(blank=True, db_comment='Indica a data base do ETL, deve buscar dados posteriores � essa data', null=True)),
            ],
            options={
                'db_table': 'tb_config_etl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbEstado',
            fields=[
                ('co_seq_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=44)),
            ],
            options={
                'db_table': 'tb_estado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbReportEtl',
            fields=[
                ('co_seq_report_etl', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_inicio_etl', models.DateTimeField(db_comment='Data do in�cio de um processo de etl')),
                ('data_fim_etl', models.DateTimeField(db_comment='Data do fim de um processo de etl')),
                ('ds_erro', models.CharField(blank=True, db_comment='Descricao de um poss�vel erro em um processo de etl', max_length=128, null=True)),
            ],
            options={
                'db_table': 'tb_report_etl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbRio',
            fields=[
                ('co_seq_rio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=144)),
                ('descricao', models.CharField(blank=True, max_length=88, null=True)),
            ],
            options={
                'db_table': 'tb_rio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbEstacao',
            fields=[
                ('co_seq_estacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_estacao', models.BigIntegerField()),
                ('codigo_bacia', models.BigIntegerField(blank=True, null=True)),
                ('codigo_sub_bacia', models.BigIntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=144, null=True)),
                ('latitude', models.CharField(blank=True, max_length=44, null=True)),
                ('longitude', models.CharField(blank=True, max_length=44, null=True)),
                ('altitude', models.CharField(blank=True, max_length=44, null=True)),
                ('operando', models.IntegerField(blank=True, db_comment='Indica se a esta��o ainda est� operando. 1 - Sim, 0 - N�o', null=True)),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
                ('co_cidade', models.ForeignKey(blank=True, db_column='co_cidade', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tbcidade')),
                ('co_rio', models.ForeignKey(blank=True, db_column='co_rio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tbrio')),
            ],
            options={
                'db_table': 'tb_estacao',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tbcidade',
            name='co_estado',
            field=models.ForeignKey(blank=True, db_column='co_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tbestado'),
        ),
        migrations.CreateModel(
            name='TbResumoMensal',
            fields=[
                ('co_seq_resumo_mensal', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_inicial', models.DateTimeField(blank=True, null=True)),
                ('data_insercao_ana', models.DateTimeField(blank=True, null=True)),
                ('metodo_obtencao', models.IntegerField(blank=True, null=True)),
                ('nivel_consistencia', models.IntegerField(blank=True, null=True)),
                ('vazao_media', models.FloatField(blank=True, null=True)),
                ('vazao_maxima', models.FloatField(blank=True, null=True)),
                ('vazao_minima', models.FloatField(blank=True, null=True)),
                ('vazao_media_real', models.FloatField(blank=True, null=True)),
                ('vazao_maxima_real', models.FloatField(blank=True, null=True)),
                ('vazao_minima_real', models.FloatField(blank=True, null=True)),
                ('co_estacao', models.ForeignKey(db_column='co_estacao', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tbestacao')),
            ],
            options={
                'db_table': 'tb_resumo_mensal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbRioCidade',
            fields=[
                ('pk', models.CompositePrimaryKey('co_rio', 'co_cidade', blank=True, editable=False, primary_key=True, serialize=False)),
                ('co_cidade', models.ForeignKey(db_column='co_cidade', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tbcidade')),
                ('co_rio', models.ForeignKey(db_column='co_rio', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tbrio')),
            ],
            options={
                'db_table': 'tb_rio_cidade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TbVazaoDiaria',
            fields=[
                ('co_seq_vazao_diaria', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_vazao', models.DateField(blank=True, null=True)),
                ('vazao', models.FloatField(blank=True, null=True)),
                ('vazao_status', models.IntegerField(blank=True, null=True)),
                ('co_resumo_mensal', models.ForeignKey(db_column='co_resumo_mensal', on_delete=django.db.models.deletion.DO_NOTHING, to='core.tbresumomensal')),
            ],
            options={
                'db_table': 'tb_vazao_diaria',
                'managed': True,
            },
        ),
    ]
