# Generated by Django 5.2.4 on 2025-07-13 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(db_column='co_seq_cidade', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=128)),
            ],
            options={
                'db_table': 'tb_cidade',
            },
        ),
        migrations.CreateModel(
            name='ConfigEtl',
            fields=[
                ('id', models.BigAutoField(db_column='co_seq_config_etl', primary_key=True, serialize=False)),
                ('parametro', models.CharField(db_column='parametro', max_length=128)),
                ('valor', models.CharField(blank=True, db_column='valor', max_length=256, null=True)),
            ],
            options={
                'db_table': 'tb_config_etl',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(db_column='co_seq_estado', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=64)),
                ('sigla', models.CharField(db_column='sigla', max_length=2)),
            ],
            options={
                'db_table': 'tb_estado',
            },
        ),
        migrations.CreateModel(
            name='ReportEtl',
            fields=[
                ('id', models.BigAutoField(db_column='co_seq_report_etl', primary_key=True, serialize=False)),
                ('data_report', models.DateTimeField(blank=True, db_column='data_report', null=True)),
                ('descricao', models.CharField(blank=True, db_column='descricao', max_length=256, null=True)),
                ('status', models.CharField(blank=True, db_column='status', max_length=32, null=True)),
            ],
            options={
                'db_table': 'tb_report_etl',
            },
        ),
        migrations.CreateModel(
            name='Rio',
            fields=[
                ('id', models.BigAutoField(db_column='co_seq_rio', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome', max_length=128)),
            ],
            options={
                'db_table': 'tb_rio',
            },
        ),
        migrations.CreateModel(
            name='Estacao',
            fields=[
                ('id', models.BigAutoField(db_column='co_seq_estacao', primary_key=True, serialize=False)),
                ('codigo_estacao', models.BigIntegerField(db_column='codigo_estacao')),
                ('codigo_bacia', models.BigIntegerField(blank=True, db_column='codigo_bacia', null=True)),
                ('codigo_sub_bacia', models.BigIntegerField(blank=True, db_column='codigo_sub_bacia', null=True)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=144, null=True)),
                ('data_insercao_ana', models.DateTimeField(blank=True, db_column='data_insercao_ana', null=True)),
                ('data_atualizacao', models.DateTimeField(blank=True, db_column='data_atualizacao', null=True)),
                ('cidade', models.ForeignKey(db_column='co_cidade', on_delete=django.db.models.deletion.PROTECT, related_name='estacoes', to='core.cidade')),
                ('rio', models.ForeignKey(db_column='co_rio', on_delete=django.db.models.deletion.PROTECT, related_name='estacoes', to='core.rio')),
            ],
            options={
                'db_table': 'tb_estacao',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(db_column='co_estado', on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='core.estado'),
        ),
        migrations.CreateModel(
            name='ResumoMensal',
            fields=[
                ('id', models.BigAutoField(db_column='co_seq_resumo_mensal', primary_key=True, serialize=False)),
                ('ano', models.IntegerField(db_column='ano')),
                ('mes', models.IntegerField(db_column='mes')),
                ('media', models.FloatField(blank=True, db_column='media', null=True)),
                ('maxima', models.FloatField(blank=True, db_column='maxima', null=True)),
                ('minima', models.FloatField(blank=True, db_column='minima', null=True)),
                ('vazoes_invalidas', models.IntegerField(blank=True, db_column='vazoes_invalidas', null=True)),
                ('estacao', models.ForeignKey(db_column='co_estacao', on_delete=django.db.models.deletion.CASCADE, related_name='resumos_mensais', to='core.estacao')),
            ],
            options={
                'db_table': 'tb_resumo_mensal',
            },
        ),
        migrations.CreateModel(
            name='VazaoDiaria',
            fields=[
                ('id', models.BigAutoField(db_column='co_seq_vazao_diaria', primary_key=True, serialize=False)),
                ('data_vazao', models.DateField(db_column='data_vazao')),
                ('vazao', models.FloatField(blank=True, db_column='vazao', null=True)),
                ('vazao_status', models.IntegerField(blank=True, db_column='vazao_status', null=True)),
                ('resumo_mensal', models.ForeignKey(db_column='co_resumo_mensal', on_delete=django.db.models.deletion.CASCADE, related_name='vazoes_diarias', to='core.resumomensal')),
            ],
            options={
                'db_table': 'tb_vazao_diaria',
            },
        ),
        migrations.CreateModel(
            name='RioCidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.ForeignKey(db_column='co_cidade', on_delete=django.db.models.deletion.CASCADE, to='core.cidade')),
                ('rio', models.ForeignKey(db_column='co_rio', on_delete=django.db.models.deletion.CASCADE, to='core.rio')),
            ],
            options={
                'db_table': 'tb_rio_cidade',
                'unique_together': {('rio', 'cidade')},
            },
        ),
    ]
