# Generated by Django 5.2.4 on 2025-07-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbCidade',
            fields=[
                ('co_seq_cidade', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=44)),
            ],
            options={
                'db_table': 'tb_cidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbConfigEtl',
            fields=[
                ('co_config_etl', models.IntegerField(primary_key=True, serialize=False)),
                ('st_ativo', models.IntegerField(db_comment='Indica se o ETL est� ativo. 1 - Ativo. 2 - Inativo')),
                ('data_atualizacao_inicial', models.DateField(blank=True, db_comment='Indica a data base do ETL, deve buscar dados posteriores � essa data', null=True)),
            ],
            options={
                'db_table': 'tb_config_etl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbEstacao',
            fields=[
                ('co_seq_estacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_estacao', models.BigIntegerField()),
                ('codigo_bacia', models.BigIntegerField(blank=True, null=True)),
                ('codigo_sub_bacia', models.BigIntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=144, null=True)),
                ('latitude', models.CharField(blank=True, max_length=44, null=True)),
                ('longitude', models.CharField(blank=True, max_length=44, null=True)),
                ('altitude', models.CharField(blank=True, max_length=44, null=True)),
                ('operando', models.IntegerField(blank=True, db_comment='Indica se a esta��o ainda est� operando. 1 - Sim, 0 - N�o', null=True)),
                ('ultima_atualizacao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_estacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbEstado',
            fields=[
                ('co_seq_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=44)),
            ],
            options={
                'db_table': 'tb_estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbReportEtl',
            fields=[
                ('co_seq_report_etl', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_inicio_etl', models.DateTimeField(db_comment='Data do in�cio de um processo de etl')),
                ('data_fim_etl', models.DateTimeField(db_comment='Data do fim de um processo de etl')),
                ('ds_erro', models.CharField(blank=True, db_comment='Descricao de um poss�vel erro em um processo de etl', max_length=128, null=True)),
            ],
            options={
                'db_table': 'tb_report_etl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbResumoMensal',
            fields=[
                ('co_seq_resumo_mensal', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_inicial', models.DateTimeField(blank=True, null=True)),
                ('data_insercao_ana', models.DateTimeField(blank=True, null=True)),
                ('metodo_obtencao', models.IntegerField(blank=True, null=True)),
                ('nivel_consistencia', models.IntegerField(blank=True, null=True)),
                ('vazao_media', models.FloatField(blank=True, null=True)),
                ('vazao_maxima', models.FloatField(blank=True, null=True)),
                ('vazao_minima', models.FloatField(blank=True, null=True)),
                ('vazao_media_real', models.FloatField(blank=True, null=True)),
                ('vazao_maxima_real', models.FloatField(blank=True, null=True)),
                ('vazao_minima_real', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_resumo_mensal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRio',
            fields=[
                ('co_seq_rio', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=144)),
                ('descricao', models.CharField(blank=True, max_length=88, null=True)),
            ],
            options={
                'db_table': 'tb_rio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRioCidade',
            fields=[
                ('pk', models.CompositePrimaryKey('co_rio', 'co_cidade', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_rio_cidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbVazaoDiaria',
            fields=[
                ('co_seq_vazao_diaria', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_vazao', models.DateField(blank=True, null=True)),
                ('vazao', models.FloatField(blank=True, null=True)),
                ('vazao_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_vazao_diaria',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='estacao',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='riocidade',
            name='cidade',
        ),
        migrations.DeleteModel(
            name='ConfigEtl',
        ),
        migrations.RemoveField(
            model_name='estacao',
            name='rio',
        ),
        migrations.RemoveField(
            model_name='resumomensal',
            name='estacao',
        ),
        migrations.DeleteModel(
            name='ReportEtl',
        ),
        migrations.RemoveField(
            model_name='vazaodiaria',
            name='resumo_mensal',
        ),
        migrations.RemoveField(
            model_name='riocidade',
            name='rio',
        ),
        migrations.AlterUniqueTogether(
            name='riocidade',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Estacao',
        ),
        migrations.DeleteModel(
            name='ResumoMensal',
        ),
        migrations.DeleteModel(
            name='VazaoDiaria',
        ),
        migrations.DeleteModel(
            name='Rio',
        ),
        migrations.DeleteModel(
            name='RioCidade',
        ),
    ]
